services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bankofcli
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
